"""CALO policy model serialization helpers with explicit trust boundaries."""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any

import torch


def checkpoint_sha256(path) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def verify_checkpoint_hash(path, expected_sha256: str | None = None) -> str:
    source = Path(path)
    actual = checkpoint_sha256(source)
    if expected_sha256 and actual.lower() != str(expected_sha256).strip().lower():
        raise ValueError(
            f"Checkpoint SHA-256 mismatch for {source.name}: expected {expected_sha256}, got {actual}"
        )
    return actual


def _validate_model_payload(payload: Any) -> dict:
    if not isinstance(payload, dict):
        raise ValueError("CALO model checkpoint must contain a dictionary payload")
    state = payload.get("model_state_dict", payload)
    if not isinstance(state, dict) or not state:
        raise ValueError("CALO model checkpoint has no model_state_dict")
    if not all(isinstance(key, str) and torch.is_tensor(value) for key, value in state.items()):
        raise ValueError("CALO model_state_dict must contain only named tensors")
    return payload


def load_checkpoint(path, *, expected_sha256: str | None = None, map_location="cpu") -> dict:
    """Load a model-only checkpoint using PyTorch's restricted weights-only unpickler."""

    source = Path(path)
    verify_checkpoint_hash(source, expected_sha256)
    payload = torch.load(source, map_location=map_location, weights_only=True)
    return _validate_model_payload(payload)


def trusted_resume_sha_path(path) -> Path:
    return Path(path).with_suffix(Path(path).suffix + ".sha256")


def write_trusted_resume_hash(path) -> str:
    source = Path(path)
    digest = checkpoint_sha256(source)
    trusted_resume_sha_path(source).write_text(digest + "\n", encoding="ascii")
    return digest


def load_trusted_resume(path, *, map_location="cpu"):
    """Load an application-created training-resume checkpoint after SHA-256 verification.

    Resume payloads contain optimizer and Python/NumPy RNG states that cannot be represented by
    the restricted weights-only format.  They are therefore accepted only when a matching sidecar
    hash generated by :func:`write_trusted_resume_hash` is present.  Untrusted downloaded resume
    files must never be opened.
    """

    source = Path(path)
    sidecar = trusted_resume_sha_path(source)
    if not sidecar.is_file():
        raise ValueError(
            "Training resume checkpoint is missing its trusted .sha256 sidecar; refusing unsafe deserialization"
        )
    expected = sidecar.read_text(encoding="ascii").strip()
    verify_checkpoint_hash(source, expected)
    return torch.load(source, map_location=map_location, weights_only=False)  # nosec B614 -- hash-verified local resume
